// Локации игры

#pragma once

#include <wchar.h>

wchar_t maps[map_count_y][map_count_x][map_height][map_width]=
{

L"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
L"RRrrrrRRRRRRRRRRRRRRRR$* п@RRRRR  $ $RRR         TT п ", // Горы
L"Rrr  rrRRRRRRRRRRRRRRR$$п $$RR                  DDRRRR",
L"RR         RR        RRSSSRRRR     п                 R",
L"R                            RR           R R         ",
L"R                             RR                      ",
L"R                              B       п       п     R",
L"R                D             BB                  RRR",
L"R               DDDR         п                  п   RR",
L"R                DRRR                     п           ",
L"R  DDDR      GG    R             GG                  G",
L"RRR D RRR  R            T     T      TT    RR        G",
L"R  DDD  RRRRR  T  T       T      TTTTTTTTRRRRRRR$$RR  ",
L"R$         *RR       TT      TTTTT            R    R R",
L"RRRRR     RRRR   TTTTTTTTRRRR                RRп  RRRR",
L"RRRRRRRRRRRRRRRRRR      RRRRRRR     RRR  $   RRRRRRRRR",

L"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
L"  $$*RRR       S$$B    @   B          B$   $B      RRR", // Лес
L"RRRRRR   $     S$$BB     BBBB         B  г  B       RR",
L"RR        п    BBBB 2     @B      г                 RR",
L"       $          B     BBBB                          ",
L"                  B     B*              R             ",
L"RRR        п      BB BBBBBB    г       BB            D",
L"RR                                    B*пB    г     DD",
L"RRRR         п        п          $   B             DDD",
L"                        T           BB B            DD",
L"GGT                      T*T T         г     г        ",
L"GGG T          R         T                            ",
L"         п   RRRR         T T                        R",
L"RRR         RRRRR   $                          R DD DR",
L"RRRRR         RR                         R R  RR   RRR",
L"RRRRRRRRRRRRRRR                     RRRRRRRRRRRRRRRRRR",

L"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWWWWWWWWWWW", 
L"R            R       R RRRRRR   RRRR          wWWWWWWW", // Побережье
L"R  RRRRRRR      RR      RR R   RRR    $     wwwwWWWWWW",
L"R       R    RRRRRR  г          RR     г      wwWWWWWW",
L"   RRR        RRR                             *ww WWWW",
L"        RRRR  RRRR      г     г           г   ww    WW",
L"D             R                    BBBBB            WW",
L"D   RRR                            B$  B  г         WW",
L"D  RR     RR   г     BBBB     г       3B        ww WWW",
L"D   R R              B$$B          B$  B  г    wwWWWWW",
L"           RR        BBSB          BBBBB       *wWWWWW",
L"       RRRRR                                  wwwwWWWW",
L"R         R                  г          г    wwwWWWWWW",
L"RRRR         г   г                             WWWWWWW",
L"RRRRRR                  DD         г        WWWWWWWWWW",
L"RRRRRRRRRRRRRRRRR      DDDD             WWWWWWWWWWWWWW",



L"RRRRRRRRRRRRRRRRRR      RRRRRRR     RRR      RRRRRRRRR", 
L"RRRRR   RRR   R         RRR          @       RRRRRRRRR", // Кузнец
L"RRRRR       т      т     RRRRRRR          RRRRRR    RR",
L"RRRRRRR  R                R   RRRRRRRRRRRRRRRRR   T  R",
L"RRRRRRRRRRRR            RRR     R Ћ≈— GGGGGGRR        ",
L"RR  ”«Ќ≈÷ RB   т    т           RRRRBBBBBBBBBB  TTT   ",
L"RBBBBBBBBBBB           B              G      G  T     ",
L"RDDDDDD               BBBB    т           T          G",
L"R 1  DDDD BB    т      B         T   т   T    TT  T TG",
L"RR        RB           BB        T         T   T  G   ",
L"RRR   RRRRRR         BBB  т     TT   G  TT     *T    G",
L"RRRRRRRRRRR         т  B                    T     T  G",
L"RRRRRR*   R                BBBBBBBBB   B   TTT  T     ",
L"RRRRRRRR     R         BBBBBB      BBBBBBBBBBBBBBBBBBB",
L"RRRRRRRRRRRRRRR    т   B    B     BB   B   B   B   B  ",
L"RRRRRRRRRRRRRRRRRRRRBBBBBBBBB      BBBBBBBBBBBBBBBBBBB",

L"RRRRRRRRRRRRRRR                     RRRRRRRRRRRRRRRRRR",
L"RRRR$$  R                                           RR", // Город Lake
L"RR R    R         BBBBBBBBB                          R",
L"R                 B  LAKE B  BB B  B BB               ",
L"   G           BBBBBBBBBBBBBBBBBB  BBBBBBBBB         R",
L"    T  G      BBк  кB5   B           ggggg B          ",
L"  T T         B$кк  B    B TTT      gBBBBBBB         R",
L"GT           BBBBBBBBBB BBBB       gBB$  B$BBB      RR",
L"G       BBBBBB2 B        B         g    4B$B*BB     RR",
L"        B$$$$B     G  G  G  BBB    gBB$  B$B$         ",
L"G       BBB BB@ B           B*B     gBBBBBBBBBB       ",
L"G        Bк  BBBB     T              gggBкк  BB       ",
L"    *B   B   к  B            B          B  кк*B       ",
L"BBBBBBBBBBк кBBBBBBB  BBBBBBBB          BBBBBBBB     R",
L" B   B   BBBBBDDDDDB  BDDDDDDBBBBBBBBBBBB           RR",
L"BBBBBBBBBB                                 RRRRRRRRRRR",

L"RRRRRRRRRRRRRRRRR      DDDD             WWWWWWWWWWWWWW",
L"RRRRR*        RRR                *       WWWWWWWWWWWWW", // Берег
L"RR             RRR  B    н     wwwwwwWWWWWWWWWWWWWWWWW",
L"     н   $$      RBBBBSSSBBBBwww  www    WWWWWWWWWWWWW",
L"R        R   н      B       w      w    WWWWWWWWWWWWWW",
L"                GGGGT      wwwwwwwww     WWWWWWWWWWWWW",
L"RRR           BBBBBBBBBB     ww           WWWWWWWWWWWW",
L"R DDD         B        B           н       WWWWWWWWWWW",
L"RRRRRR       BBBBBBBBBBBBBBBB               WWWWWWWWWW",
L"     R       B   6  BB*     S      R        WWWWWWWWWW",
L"         TT         BB@  н  B          н   WWWWWWWWWWW",
L"       R     BBBBBBBBBBBBBBBB     $$      WWWWWWWWWWWW",
L"            TT       $$$                 WWWWWWWWWWWWW",
L"R           T   н    $$$       н        WWWWWWWWWWWWWW",
L"RRRRR   н  TT                          WWWWWWWWWWWWWWW",
L"RRRRRRRRRRR T                        WWWWWWWWWWWWWWWWW",

L"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBBBBB",
L"RBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBR", // Заброшенная шахта
L"RB    *BBBB    B                   B     B$         BR",
L"RB 0      BBB BBBBB     BBBBBBBBBBBB  г  BBB BBB    BB",
L"RB    *B       *B$       $B      $BB           B  п BB",
L"RBBBBBBB    н   B$   н            BB    BBBBBBBBB BBBB",
L"RB@    B        BBB     BBB    г *B        п   B     B",
L"RB  з  B    BBBBB   н     B$      B    г      п       ",
L"RBB   BB                  B      $B       B           ",
L"RB          н   BB     BBBB    BBBBB   BBBBBBBBB  п  B",
L"RBB   BB       BB$      B      B       BB  *   BBB BBB",
L"RB  з  BBB      B       B  г        г          B    $B",
L"RB     B$   н   B     BBBBB             B   п       BB",
L"RB з   B$       B*             B       $B      B   $BR",
L"RBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBR",
L"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",

L"BBBBBBBBBB                                 RRRRRRRRRRR",
L"RRR      B                                 B     RRRRR", // Кладбище
L"RRBBBBBBBB   B                       $$    B      RRRR",
L"B    з   BBBBBBBBBBBBBBBBBBSSBBBBSSBBBBBBBBB  $$   RRR",
L"B  з     B            B              B     B          ",
L"BBB    BBBBBBBBBBBBBBBB   !   !   !                   ",
L"B      B   *  @    з  B              B           з    ",
L"    з  B              BB   BBBB  BBBBB    з           ",
L"       B  !  !  !             B                       ",
L"BB     B              B    !  !      BB BB    з       ",
L"B         !  !  !     B              B   B            ",
L"BR  $                 B    !  !    з B   B        BBBB",
L"BRR               BBBBB              BBBBB     з  B*  ",
L"RRRRR       з                   з                     ",
L"RRRRRRRRR           WWWWWW          WWWWWWWWWWWWWWWWWW",
L"RRRRRRRRRR WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",

L"RRRRRRRRRRR G                        WWWWWWWWWWWWWWWWW",
L"RRRRRRRRRRRRR             *          WWWWWWWWWWWWWWWWW", // Логово дракона
L"RRR        RRW                     WWWWWWWWWWWWWWWWWWW",
L"R           WWWWWWWWWWWWW    WWWWWWWWWWWWWWWWWWWWWWWWW",
L"              WWWWWW    WWWWWWWW          B д   WWWWWW",
L"               WWWW                      B BB   WWWWWW",
L"                WW               *B     B    B  WWWWWW",
L"      $                          BBB   *BBB     WWWWWW",
L"      $         7                 B   BBB        WWWWW",
L"                                     BB BB  B    WWWWW",
L"                WW                   B          WWWWWW",
L"BB             WWWWWBB    B      B      BB    WWWWWWWW",
L"             WWWWWWWBB    B@                WWWWWWWWWW",
L"           WWWWWWWWWWWWWW BBB           WWWWWWWWWWWWWW",
L"WWWWWWWWWWWWWWWWWWWWWWWWW WW     WWWWWWWWWWWWWWWWWWWWW",
L"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"

};
